package transactions

import (
	ristretto "github.com/bwesterb/go-ristretto"
	"github.com/dusk-network/dusk-wallet/key"
)

// NoteOutputObfuscated is a note with an zk-obfuscated value
type NoteOutputObfuscated struct {
	// Commitments are generated by the ZK engine for the value proof.
	Commitments []ristretto.Point

	// Value represents the encrypted output value with PKr
	Value []byte

	// B represents the encrypted blinding factor of the generated commitment.
	B []byte

	// R is the randomness for the key generation.
	//
	// R := r . G
	R ristretto.Point

	// PubKey is a one-time pubkey that refers to the owner
	// of the note.
	//
	// PrivateSpend := scalarDerive(H(r))
	// PrivateView := scalarDerive(H(PrivateSpend))
	// PublicSpend := PrivateSpend . G
	// PublicView := PrivateView . G
	// PubKey := { PublicSpend, PublicView }
	PubKey key.StealthAddress

	// Idx refers to the position of the note in the tree.
	Idx uint64
}

// Transparent is false for obfuscated notes
func (no *NoteOutputObfuscated) Transparent() bool {
	return false
}
